### ISSUE TITLE
#1 Display Card

### ISSUE THREAD

**Issue by Nimbaland** [Nimbaland/Capstone-Project-Flow#1]
## Value Proposition

**As a** User 
**I want to** see a random Yoga/Asana pose
**so that** i get inspiration for my own yoga flow.

## Description

![Image](https://user-images.githubusercontent.com/113900605/203529244-17143ccb-91cf-4e89-acdc-61ad64cb2cad.png)

## Acceptance Criteria

- [x] a Headline with the title of the app is displayed 
- [x] a random Card/Asana is displayed
- [x] the Card contains a  Yoga/Asana pose as an Image
- [x] the Card contains the Name of the Yoga/Asana pose
- [x] when reloading the page a different Yoga/Asana pose is displayed

## Tasks

- [x] create a feature/branch `feature/displayCard`
- [x] add headline 
- [x] create `Dummy Data` for the different Yoga/Asana poses
- [x] create a `Yoga/AsanaCard` component to display a random `image` and `yoga/asana title` from `Dummy`
- [x] create functionallity for the first random Yoga/Asana pose Card

## Complexity

- M
