### ISSUE TITLE
#2 Add Yes & No Button

### ISSUE THREAD

**Issue by Nimbaland** [Nimbaland/Capstone-Project-Flow#3]
## Value Proposition

**As a** user
**I want to** choose my Yoga/Asana Pose Card
**so that** i create my own Flow

## Description

![Image](https://user-images.githubusercontent.com/113900605/203810138-13097902-0021-4268-8c63-d254255ffe99.png)

## Acceptance Criteria

- [x] Yoga/Asana Card is displayed on the index page
- [x] button with "No" & "Yes" icon with no function 

## Tasks
- [x] create a feature branch
- [x] use the existing card component to display the Yoga/Asanas from the db.json
- [x] create a round button with "Yes" Icon
- [x] create a round button with "No" icon 

## Complexity

- s
