### ISSUE TITLE
#3 Create Local Storage / Flowdeck

### ISSUE THREAD

**Issue by Nimbaland** [Nimbaland/Capstone-Project-Flow#4]
## Value Proposition

**As a** user
**I want to** choose my Yoga/Asana Pose Card
**so that** i create my own Flow

## Description

![Image](https://user-images.githubusercontent.com/113900605/203812404-df0b5320-fff7-4360-b48e-f45f88de358c.png)

`Please, do not pay attention to the navbar. I have shortened the UserStory 3.`

## Acceptance Criteria

- [x] Yoga/Asana Card is displayed on the index page

## Tasks

- [x] create a feature branch
- [x] create a Flowdeck Page 
- [x] create a local storage

## Complexity

- M

**Comment by actyvystom** [comment]
Hi Nimba,
as far as I understand your US, I guess your wireframe pic does not match to the story... you mention Yes and No buttons in your acceptance criteria, but I don't see any of them in the wireframe ;) 
Also the task list does not include the creation of them.

**Comment by aplasa85** [comment]
Looks good!
