### ISSUE TITLE
#Navbar

### ISSUE THREAD

**Issue by Nimbaland** [Nimbaland/Capstone-Project-Flow#6]
**As a** user
**I want to** choose between index & flowdeck
**so that** i create my own Flow or check my flow

## Description

![Image](https://user-images.githubusercontent.com/113900605/203812404-df0b5320-fff7-4360-b48e-f45f88de358c.png)

`Please, do not pay attention to the flowdeck. I have shortened the UserStory 3.`

## Acceptance Criteria

- [ ] the first Flowdeck is displayed with Yoga/Asana Card on the `Flowdeck Page` 
- [ ] At the bottom of the page is a navigation to switch between the `Index Page` and `Flowdeck Page`.
- [ ] `The Page`, where the user is `currently on`, is `highlighted` in the `navigation`
- [ ] when the `button` called `Yes` is clicked the current Yoga/Asana Card is `bookmarked` and `displayed` on the `Flowdeck Page` and the next Yoga/Asana Card render on `Index Page`
- [ ] after the `button` called `No` is clicked the next `Yoga/Asana Card` render on `Index Page`

## Tasks
- [ ] create a feature branch
- [ ] create  a  first Flowdeck 
- [ ] add a navbar 
- [ ] create a round button with an Icon  for Index Page 
- [ ] create a round button with an icon for Flowdeck Page
- [ ] create a eventHandler function to bookmark the Flow on buttonclick
- [ ] add links to the navbar items
- [ ] navbar item is highlighted when i´m on the page

## Sizing/Complexity

L

**Comment by SergeyMOV** [comment]
Looks Good!
